package interfaz;

public class Cancion__bloque_con_opciones_ extends Cancion {
//	private Button _opcionesB;
	public Lista_canciones _lista_canciones;
	public Opciones_cancion__cancion_ _opciones_cancion__cancion_;
	public Reproducir_cancion_cibernauta_registrado _reproducir_cancion_cibernauta_registrado;
	public Reproductor_resumido__usuario_registrado_ _reproductor_resumido__usuario_registrado_;
}