package interfaz;

import vistas.VistaListas_de_reproduccion_del_artista;

public class Listas_de_reproduccion_del_artista extends VistaListas_de_reproduccion_del_artista{
	public Ver_perfil_artista _ver_perfil_artista;
	public Lista_del_artista _lista_del_artista;
}