package interfaz;

import java.util.Vector;
import interfaz.Artista__bloque_administrador_;
import vistas.VistaLista_de_artistas_buscados_administrador;

public class Lista_de_artistas_buscados__administrador_ extends VistaLista_de_artistas_buscados_administrador{
	public Buscador_administrador _buscador_administrador;
	public Vector<Artista__bloque_administrador_> _list_Artista__bloque_administrador_ = new Vector<Artista__bloque_administrador_>();
}