package interfaz;

import java.util.Vector;
import interfaz.Perfil__bloque_administrador_;
import vistas.VistaLista_de_perfiles_buscados_administrador;

public class Lista_de_perfiles_buscados__administrador_ extends VistaLista_de_perfiles_buscados_administrador{
	public Buscador_administrador _buscador_administrador;
	public Vector<Perfil__bloque_administrador_> _list_Perfil__bloque_administrador_ = new Vector<Perfil__bloque_administrador_>();
}