package interfaz;

import java.util.Vector;
import interfaz.Cancion__lista_administrador_;
import vistas.VistaLista_de_canciones_ver_todo_administrador;

public class Lista_de_canciones__ver_todo_administrador_ extends VistaLista_de_canciones_ver_todo_administrador{
	public Ver_todas_canciones_buscadas__administrador_ _ver_todas_canciones_buscadas__administrador_;
	public Vector<Cancion__lista_administrador_> _list_Cancion__lista_administrador_ = new Vector<Cancion__lista_administrador_>();
}