package interfaz;

import vistas.VistaLista_de_reproduccion_bloque;

public class Lista_de_reproduccion__bloque_ extends VistaLista_de_reproduccion_bloque{
	public Listas_de_reproduccion__ver_todo_ _listas_de_reproduccion__ver_todo_;
	public Ver_lista_de_reproduccion_ajena _ver_lista_de_reproduccion_ajena;
}