package interfaz;

import java.util.Vector;
import interfaz.Perfil__lista_administrador_;
import vistas.VistaLista_de_perfiles_ver_todo_administrador;

public class Lista_de_perfiles__ver_todo_administrador_ extends VistaLista_de_perfiles_ver_todo_administrador{
	public Ver_todos_perfiles_buscados__administrador_ _ver_todos_perfiles_buscados__administrador_;
	public Vector<Perfil__lista_administrador_> _list_Perfil__lista_administrador_ = new Vector<Perfil__lista_administrador_>();
}