package interfaz;

import java.util.Vector;
import interfaz.Artista__lista_administrador_;
import vistas.VistaLista_de_artistas_ver_todo_administrador;

public class Lista_de_artistas__ver_todo_administrador_ extends VistaLista_de_artistas_ver_todo_administrador{
	public Ver_todos_los_artistas_buscados__administrador_ _ver_todos_los_artistas_buscados__administrador_;
	public Vector<Artista__lista_administrador_> _list_Artista__lista_administrador_ = new Vector<Artista__lista_administrador_>();
}