package interfaz;

import java.util.Vector;
import interfaz.Album__lista_administrador_;
import vistas.VistaLista_de_albumes_ver_todo_administrador;

public class Lista_de_albumes__ver_todo_administrador_ extends VistaLista_de_albumes_ver_todo_administrador{
	public Ver_todos_los_albumes_buscados__administrador_ _ver_todos_los_albumes_buscados__administrador_;
	public Vector<Album__lista_administrador_> _list_Album__lista_administrador_ = new Vector<Album__lista_administrador_>();
}