package interfaz;

public class Reproductor_resumido__usuario_registrado_ extends Reproductor_resumido {
	public Comun _comun;
	public Cancion__lista_ _cancion__lista_;
	public Cancion__bloque_con_opciones_ _cancion__bloque_con_opciones_;
	public Reproducir_cancion_cibernauta_registrado _reproducir_cancion_cibernauta_registrado;
}