package interfaz;

import vistas.VistaVer_todos_los_artistas_buscados_administrador;

public class Ver_todos_los_artistas_buscados__administrador_ extends VistaVer_todos_los_artistas_buscados_administrador {
	public Buscador_administrador _buscador_administrador;
	public Lista_de_artistas__ver_todo_administrador_ _lista_de_artistas__ver_todo_administrador_;
}