package interfaz;

public class Ver_todos_los_artistas_buscados__administrador_ extends Barra_buscador {
	public Buscador_administrador _buscador_administrador;
	public Lista_de_artistas__ver_todo_administrador_ _lista_de_artistas__ver_todo_administrador_;
}