package interfaz;

import vistas.VistaVer_todos_perfiles_buscados_administrador;

public class Ver_todos_perfiles_buscados__administrador_ extends VistaVer_todos_perfiles_buscados_administrador {
	public Buscador_administrador _buscador_administrador;
	public Lista_de_perfiles__ver_todo_administrador_ _lista_de_perfiles__ver_todo_administrador_;
}