package interfaz;

public class Ver_todos_los_albumes_buscados__administrador_ extends Barra_buscador {
	public Buscador_administrador _buscador_administrador;
	public Lista_de_albumes__ver_todo_administrador_ _lista_de_albumes__ver_todo_administrador_;
}